name: CI/CD Terraform AWS

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'app/**'
      - 'infra/terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      assume-role: ${{ steps.set-role.outputs.assume-role }}
      environment: ${{ steps.set-role.outputs.environment }}
    steps:
      - name: Define AWS Assume Role
        id: set-role
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "assume-role=${{ secrets.PROD_AWS_ASSUME_ROLE_ARN }}" >> $GITHUB_OUTPUT
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "assume-role=${{ secrets.DEV_AWS_ASSUME_ROLE_ARN }}" >> $GITHUB_OUTPUT
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi

  validate:
    name: Terraform Validate
    needs: setup
    uses: ./.github/workflows/terraform-validate.yml
    with:
      aws-region: 'us-east-1'
      environment: ${{ needs.setup.outputs.environment }}
      aws-assume-role-arn: ${{ secrets.DEV_AWS_ASSUME_ROLE_ARN }}
    secrets:  # Isso é necessário para workflows reutilizáveis
      DEV_AWS_ASSUME_ROLE_ARN: ${{ secrets.DEV_AWS_ASSUME_ROLE_ARN }}

  deploy:
    name: Terraform Apply
    needs: [setup, validate]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    uses: ./.github/workflows/terraform-apply.yml
    with:
      aws-region: 'us-east-1'
      environment: ${{ needs.setup.outputs.environment }}
      aws-assume-role-arn: ${{ needs.setup.outputs.assume-role }}
