name: CI/CD Terraform AWS

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
    paths:
      - 'app/**'
      - 'infra/terraform/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'app/**'
      - 'infra/terraform/**'

jobs:
  validate:
    name: Terraform Validate
    uses: ./.github/workflows/terraform-validate.yml
    with:
      aws-assume-role-arn: ${{ github.ref == 'refs/heads/main' && secrets.PROD_AWS_ASSUME_ROLE_ARN || secrets.DEV_AWS_ASSUME_ROLE_ARN }}

  deploy:
    name: Terraform Apply
    needs: validate
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    uses: ./.github/workflows/terraform-apply.yml
    with:
      aws-assume-role-arn: ${{ github.ref == 'refs/heads/main' && secrets.PROD_AWS_ASSUME_ROLE_ARN || secrets.DEV_AWS_ASSUME_ROLE_ARN }}
