name: Terraform CI/CD Orchestrator

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'app/**'
      - 'infra/terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setup.outputs.environment }}

    steps:
      - name: Determine Environment and Role
        id: setup
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_name }}" == "main" ]] || \
             [[ "${{ github.event_name }}" == "pull_request" && "${{ github.base_ref }}" == "main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
            echo "aws_role_arn=${{ secrets.PROD_AWS_ASSUME_ROLE_ARN }}" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "aws_role_arn=${{ secrets.DEV_AWS_ASSUME_ROLE_ARN }}" >> $GITHUB_OUTPUT
          fi

      - name: Call Reusable Validate Workflow
        uses: ./.github/workflows/terraform-validate.yml
        with:
          environment: ${{ steps.setup.outputs.environment }}
          aws-assume-role-arn: ${{ steps.setup.outputs.aws_role_arn }}
          aws-region: 'us-east-1'
        # A linha "secrets: inherit" foi removida daqui, pois é inválida em um "step"

  deploy-dev:
    needs: validate
    runs-on: ubuntu-latest # <-- MUDANÇA: Job agora é "normal"
    if: github.event_name == 'push' && github.ref_name == 'develop' && needs.validate.outputs.environment == 'dev'
    steps: # <-- MUDANÇA: Adicionado bloco de steps
      - name: Call Reusable Apply Workflow for Dev
        uses: ./.github/workflows/terraform-apply.yml
        with:
          environment: 'dev'
          aws-assume-role-arn: ${{ secrets.DEV_AWS_ASSUME_ROLE_ARN }}
          aws-region: 'us-east-1'

  deploy-prod:
    needs: validate
    runs-on: ubuntu-latest # <-- MUDANÇA: Job agora é "normal"
    if: github.event_name == 'push' && github.ref_name == 'main' && needs.validate.outputs.environment == 'prod'
    steps: # <-- MUDANÇA: Adicionado bloco de steps
      - name: Call Reusable Apply Workflow for Prod
        uses: ./.github/workflows/terraform-apply.yml
        with:
          environment: 'prod'
          aws-assume-role-arn: ${{ secrets.PROD_AWS_ASSUME_ROLE_ARN }}
          aws-region: 'us-east-1'