name: CI/CD Terraform AWS

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
    paths:
      - 'app/**'
      - 'infra/terraform/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'app/**'
      - 'infra/terraform/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      assume-role: ${{ steps.set-role.outputs.assume-role }}
    steps:
      - name: Define AWS Assume Role
        id: set-role
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "assume-role=${{ secrets.PROD_AWS_ASSUME_ROLE_ARN }}" >> $GITHUB_OUTPUT
          else
            echo "assume-role=${{ secrets.DEV_AWS_ASSUME_ROLE_ARN }}" >> $GITHUB_OUTPUT
          fi

  validate:
    name: Terraform Validate
    needs: setup
    uses: ./.github/workflows/terraform-validate.yml
    secrets:
      aws-assume-role-arn: ${{ needs.setup.outputs.assume-role }}

  deploy:
    name: Terraform Apply
    needs: [setup, validate]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    uses: ./.github/workflows/terraform-apply.yml
    secrets:
      aws-assume-role-arn: ${{ needs.setup.outputs.assume-role }}
