name: MANUAL - Destroy Terraform Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente que será destruído'
        required: true
        type: choice
        options:
          - dev
          - prod
      confirm:
        description: 'Digite "destruir" para confirmar a operação.'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  # Job para destruir o ambiente de desenvolvimento
  destroy-dev:
    if: inputs.confirm == 'destruir' && inputs.environment == 'dev'
    runs-on: ubuntu-latest # <-- MUDANÇA
    steps: # <-- MUDANÇA
      - name: Destroy Workflow for Dev
        uses: ./.github/workflows/terraform-destroy.yml
        with:
          environment: 'dev'
          aws-assume-role-arn: ${{ secrets.DEV_AWS_ASSUME_ROLE_ARN }}
          aws-region: 'us-east-1'

  # Job para destruir o ambiente de produção
  destroy-prod:
    if: inputs.confirm == 'destruir' && inputs.environment == 'prod'
    runs-on: ubuntu-latest # <-- MUDANÇA
    steps: # <-- MUDANÇA
      - name: Destroy Workflow for Prod
        uses: ./.github/workflows/terraform-destroy.yml
        with:
          environment: 'prod'
          aws-assume-role-arn: ${{ secrets.PROD_AWS_ASSUME_ROLE_ARN }}
          aws-region: 'us-east-1'
    
  # Job para cancelar a execução se a confirmação estiver errada
  cancel-if-not-confirmed:
    if: inputs.confirm != 'destruir'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflow
        run: |
          echo "::error::Ação cancelada. A confirmação 'destruir' não foi inserida corretamente."
          exit 1