name: Terraform Validate

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      aws-region:
        type: string
        required: false
        default: 'us-east-1'
    secrets:
      aws-assume-role-arn:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-assume-role-arn }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws-region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        working-directory: infra/terraform
        run: |
          terraform init \
            -var="environment=${{ inputs.environment }}" \
            -backend-config="bucket=notifyuploadcomplete-terraform-tfstates-${{ inputs.environment }}" \
            -backend-config="key=${{ github.event.repository.name }}/${{ inputs.environment }}" \
            -backend-config="region=${{ inputs.aws-region }}"

      - name: Select or Create Workspace
        working-directory: infra/terraform
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Terraform Validate
        working-directory: infra/terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra/terraform
        run: |
          terraform plan \
            -var-file="./${{ inputs.environment }}/terraform.tfvars" \
            -out="${{ inputs.environment }}.plan"