name: "[PROD] CI/CD Terraform AWS"

on:
  push:
    branches: [main]    

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Terraform Validate
    uses: ./.github/workflows/terraform-validate.yml
    with:
      environment: 'prod'
      is_develop_or_main_branch: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    secrets:
      aws-assume-role-arn: ${{ secrets.PROD_AWS_ASSUME_ROLE_ARN }}

  deploy:
    name: Terraform Apply
    needs: [validate]
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: 'prod'
      github_environment: 'production'
    secrets:
      aws-assume-role-arn: ${{ secrets.PROD_AWS_ASSUME_ROLE_ARN }}