name: CI/CD Terraform AWS

on:
  push:
    branches: [develop]

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Terraform Validate
    uses: ./.github/workflows/terraform-validate.yml
    with:
      environment: 'dev'
    secrets:
      aws-assume-role-arn: ${{ secrets.DEV_AWS_ASSUME_ROLE_ARN }}

  deploy:
    name: Terraform Apply
    needs: validate
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: 'dev'      
    secrets:
      aws-assume-role-arn: ${{ secrets.DEV_AWS_ASSUME_ROLE_ARN }}
  
  create_pr:
    runs-on: ubuntu-latest
    needs: [ validate, deploy ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'Automatic PR: Merge changes to main'
          branch: ${{ github.ref }}
          base: main
          title: 'Automatic PR from ${{ github.ref }}'
          body: |
            Este PR foi criado automaticamente pelo fluxo de trabalho de CI para mesclar alterações de ${{ github.ref }} para main.