name: CI/CD Terraform AWS

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'infra/**'
    

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Terraform Validate
    uses: ./.github/workflows/terraform-validate.yml
    with:
      environment: 'prod'
      lambda_bucket_name: ${{ needs.bootstrap.outputs.lambda_bucket_name }}
    secrets:
      aws-assume-role-arn: ${{ secrets.PROD_AWS_ASSUME_ROLE_ARN }}

  deploy:
    name: Terraform Apply
    needs: [validate]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: 'prod'
      github_environment: 'production'
    secrets:
      aws-assume-role-arn: ${{ secrets.PROD_AWS_ASSUME_ROLE_ARN }}
      lambda_bucket_name: ${{ secrets.TF_LAMBDA_BUCKET_NAME }}