name: "[FEATURE] CI/CD Terraform AWS"

on:
  push:
    branches: ['feature/**']    

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Terraform Validate
    uses: ./.github/workflows/terraform-validate.yml
    with:
      environment: 'dev'
      is_develop_or_main_branch: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    secrets:
      aws-assume-role-arn: ${{ secrets.DEV_AWS_ASSUME_ROLE_ARN }}
  
  create_pr:
    runs-on: ubuntu-latest
    needs: [ validate ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'Automatic PR: Merge changes to develop'
          branch: ${{ github.ref }}
          base: develop
          title: 'Automatic PR from ${{ github.ref }}'
          body: |
            Este PR foi criado automaticamente pelo fluxo de trabalho de CI para mesclar alterações de ${{ github.ref }} para develop.